CREATE TABLE MENSAGEM
  (
    COD_MSG INTEGER PRIMARY KEY,
    DESC_MSG VARCHAR(300) NOT NULL,
    FK_USER INTEGER NOT NULL,
    FOREIGN KEY (FK_USER) REFERENCES USUARIOS(COD_USUARIO)
  );

CREATE TABLE USUARIOS
  (
    COD_USUARIO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(32) NOT NULL
  );